{% set name = "snowpark-checkpoints" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/snowflakedb/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f81ea8a6fa3ffc94e2029771f4f0bc1f8fb00742b0295745a99f285368daa98a

build:
  # https://github.com/snowflakedb/snowpark-checkpoints/blob/v0.1.4/pyproject.toml#L15
  # From the upstream repository: requires-python = '>=3.9,<3.12'
  skip: True  # [py<39 or py>311 or s390x]
  script: {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation
  number: 100

requirements:
  host:
    - python
    - hatchling
    - pip
    - wheel
  run:
    - python
    - pandera-io ==0.20.4
    - hypothesis
    - snowflake-snowpark-python ==1.23.0
    - snowflake-connector-python
  run_constrained:
    - pyspark >=3.5.0

# Tests from snowpark-checkpoints-validators/test that require connection with snowflake
{% set tests_to_skip_validators = "test_input" %}
{% set tests_to_skip_validators = tests_to_skip_validators + " or test_input_fail" %}
{% set tests_to_skip_validators = tests_to_skip_validators + " or test_output" %}
{% set tests_to_skip_validators = tests_to_skip_validators + " or test_output_fail" %}
{% set tests_to_skip_validators = tests_to_skip_validators + " or test_df_check" %}
{% set tests_to_skip_validators = tests_to_skip_validators + " or test_df_check_fail" %}
{% set tests_to_skip_validators = tests_to_skip_validators + " or test_df_check_from_file" %}
{% set tests_to_skip_validators = tests_to_skip_validators + " or test_df_check_custom_check" %}
{% set tests_to_skip_validators = tests_to_skip_validators + " or test_df_check_skip_check" %}
{% set tests_to_skip_validators = tests_to_skip_validators + " or test_df_mode_dataframe" %}
{% set tests_to_skip_validators = tests_to_skip_validators + " or test_df_mode_dataframe_mismatch" %}
{% set tests_to_skip_validators = tests_to_skip_validators + " or test_df_mode_dataframe_job_none" %}
{% set tests_to_skip_validators = tests_to_skip_validators + " or test_df_mode_dataframe_invalid_mode" %}
{% set tests_to_skip_validators = tests_to_skip_validators + " or test_spark_checkpoint_scalar_passing" %}
{% set tests_to_skip_validators = tests_to_skip_validators + " or test_spark_checkpoint_scalar_fail" %}
{% set tests_to_skip_validators = tests_to_skip_validators + " or test_spark_checkpoint_df_pass" %}
{% set tests_to_skip_validators = tests_to_skip_validators + " or test_spark_checkpoint_df_fail" %}
{% set tests_to_skip_validators = tests_to_skip_validators + " or test_spark_checkpoint_limit_sample" %}
{% set tests_to_skip_validators = tests_to_skip_validators + " or test_spark_checkpoint_random_sample" %}

test:
  source_files:
    - snowpark-checkpoints-collectors/test
    - snowpark-checkpoints-configuration/test
    - snowpark-checkpoints-hypothesis/test
    - snowpark-checkpoints-validators/test
  imports:
    - snowflake.snowpark_checkpoints
    - snowflake.snowpark_checkpoints_collector
    - snowflake.snowpark_checkpoints_configuration
    - snowflake.hypothesis_snowpark
  commands:
    - pip check
    # Skipping snowpark-checkpoints-collectors/test as most of the tests require Java gateway
    # - pytest -vv snowpark-checkpoints-collectors/test
    - pytest -vv snowpark-checkpoints-configuration/test
    # snowpark-checkpoints-validators/test/unit/test_spark_migration.py - require Java gateway
    - pytest -vv snowpark-checkpoints-validators/test -k "not ({{ tests_to_skip_validators }})" --ignore="snowpark-checkpoints-validators/test/unit/test_spark_migration.py"
    # Needs cd-ing as it's using resources inside with relative paths
    # test/integ/test_strategies.py - missing some resources
    # test/unit/test_strategies_utils.py - trying to connect with snowflake
    - cd snowpark-checkpoints-hypothesis && pytest -vv test --ignore="test/integ/test_strategies.py" --ignore="test/unit/test_strategies_utils.py" -k "not test_pandera_dtype_to_snowpark_dtype_long"
  requires:
    - pip
    - pytest
    - deepdiff
    - pyspark >=3.5.0

about:
  home: https://github.com/snowflakedb/snowpark-checkpoints
  summary: Snowflake Snowpark Checkpoints
  dev_url: https://github.com/snowflakedb/snowpark-checkpoints
  doc_url: https://docs.snowflake.com/en/developer-guide/snowpark/python/snowpark-checkpoints-library
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: |
    The snowpark-checkpoints package is a testing library that will help you validate your migrated Snowpark
    code and discover any behavioral differences with the original Apache PySpark code.

extra:
  recipe-maintainers:
    - Cansisti
